services:

  wrychain_adminer_production:
    build:
      context: ./
      dockerfile: ./docker/production/adminer/Dockerfile
    container_name: wrychain_adminer_production
    depends_on:
      - wrychain_mssql_production
    env_file:
      - ./docker/production/adminer/.env.local
    image: wrychain_adminer_production
    ports:
      - 8000:8080
    networks:
      - wrychain_production

  wrychain_aspnet_production:
    build:
      context: ./
      dockerfile: ./docker/production/aspnet/Dockerfile
    container_name: wrychain_aspnet_production
    depends_on:
      - wrychain_mssql_production
    env_file:
      - ./docker/production/aspnet/.env.local
    image: wrychain_aspnet_production
    networks:
      - wrychain_production

  wrychain_mssql_production:
    build:
      context: ./
      dockerfile: ./docker/production/mssql/Dockerfile
    container_name: wrychain_mssql_production
    env_file:
      - ./docker/production/mssql/.env.local
    image: wrychain_mssql_production
    volumes:
      - ./docker/production/mssql/data:/var/opt/mssql/data
    networks:
      - wrychain_production

  wrychain_nginx_production:
    container_name: wrychain_nginx_production
    build:
      context: ./
      dockerfile: docker/production/nginx/Dockerfile
    depends_on:
      - wrychain_aspnet_production
    image: wrychain_nginx_production
    ports:
      - 443:443
    volumes:
      - ./docker/production/nginx/logs:/var/log/nginx
    networks:
      # - reproxy
      - wrychain_production

  wrychain_vue_production:
    build:
      context: ./
      dockerfile: ./docker/production/vue/Dockerfile
    container_name: wrychain_vue_production
    depends_on:
      - wrychain_aspnet_production
    env_file:
      - ./docker/production/vue/.env.local
    image: wrychain_vue_production
    networks:
      - wrychain_production

networks:

  wrychain_production:
    name: wrychain_production
    driver: bridge

  # reproxy:
  #   external: true
  #   name: reproxy
