services:

  ##############################################################
  # Development                                                #
  ##############################################################

  # Nginx development reverse proxy

  caspnetti_nginx_development:
    container_name: caspnetti_nginx_development
    build:
      context: ./
      dockerfile: docker/nginx_development/Dockerfile
    depends_on:
      - caspnetti_aspnet_development
    image: caspnetti_nginx_development
    ports:
      - 443:443
    volumes:
      - ./logs/nginx_development:/var/log/nginx
    networks:
      # Production reverse proxy
      # - reproxy
      - caspnetti
    # restart: unless-stopped

  # Aspnetcore development

  caspnetti_aspnet_development:
    build:
      context: ./
      dockerfile: ./docker/aspnet_development/Dockerfile
    container_name: caspnetti_aspnet_development
    depends_on:
      - caspnetti_mssql_development
    env_file:
      - ./docker/aspnet_development/.env.local
    image: caspnetti_aspnet_development
    volumes:
      - ./src/backend:/caspnetti
    networks:
      - caspnetti

  # MSSQL development database

  caspnetti_mssql_development:
    build:
      context: ./
      dockerfile: ./docker/mssql_development/Dockerfile
    container_name: caspnetti_mssql_development
    env_file:
      - ./docker/mssql_development/.env.local
    image: caspnetti_mssql_development
    volumes:
      - ./data/mssql_development:/var/opt/mssql/data
    networks:
      - caspnetti

  # Adminer database viewer

  caspnetti_adminer:
    build:
      context: ./
      dockerfile: ./docker/adminer/Dockerfile
    container_name: caspnetti_adminer
    depends_on:
      - caspnetti_mssql_development
    env_file:
      - ./docker/adminer/.env.local
    image: caspnetti_adminer
    ports:
      - 8000:8080
    networks:
      - caspnetti

  # Vuejs frontend

  caspnetti_vue_development:
    build:
      context: ./
      dockerfile: ./docker/vue_development/Dockerfile
    container_name: caspnetti_vue_development
    depends_on:
      - caspnetti_aspnet_development
    env_file:
      - ./docker/vue_development/.env.local
    image: caspnetti_vue_development
    ports:
      - 8080:8080
    volumes:
      - ./src/frontend:/caspnetti
    networks:
      - caspnetti

  ##############################################################
  # Production                                                 #
  ##############################################################

  # # Nginx production reverse proxy

  # caspnetti_nginx_production:
  #   container_name: caspnetti_nginx_production
  #   build:
  #     context: ./
  #     dockerfile: docker/nginx_production/Dockerfile
  #   depends_on:
  #     - caspnetti_aspnet_production
  #   image: caspnetti_nginx_production
  #   ports:
  #     - 443:443
  #   volumes:
  #     - ./logs/nginx_production:/var/log/nginx
  #   networks:
  #     # Production reverse proxy
  #     # - reproxy
  #     - caspnetti
  #   # restart: unless-stopped

  # # Aspnetcore production

  # caspnetti_aspnet_production:
  #   build:
  #     context: ./
  #     dockerfile: ./docker/aspnet_production/Dockerfile
  #   container_name: caspnetti_aspnet_production
  #   depends_on:
  #     - caspnetti_mssql_production
  #   env_file:
  #     - ./docker/aspnet_production/.env.local
  #   image: caspnetti_aspnet_production
  #   networks:
  #     - caspnetti

  # # MSSQL production database

  # caspnetti_mssql_production:
  #   build:
  #     context: ./
  #     dockerfile: ./docker/mssql_production/Dockerfile
  #   container_name: caspnetti_mssql_production
  #   env_file:
  #     - ./docker/mssql_production/.env.local
  #   image: caspnetti_mssql_production
  #   volumes:
  #     - ./data/mssql_production:/var/opt/mssql/data
  #   networks:
  #     - caspnetti

  # # Vue + nginx production frontend

  # caspnetti_vue_production:
  #   build:
  #     context: ./
  #     dockerfile: ./docker/vue_production/Dockerfile
  #   container_name: caspnetti_vue_production
  #   depends_on:
  #     - caspnetti_aspnet_production
  #   env_file:
  #     - ./docker/vue_production/.env.local
  #   image: caspnetti_vue_production
  #   ports:
  #     - 80:80
  #   networks:
  #     - caspnetti

  ##############################################################
  # Utilities                                                  #
  ##############################################################

  # # Saturation testing

  # caspnetti_hey:
  #   build:
  #     context: ./
  #     dockerfile: ./docker/hey/Dockerfile
  #   container_name: caspnetti_hey
  #   depends_on:
  #     - caspnetti_aspnet_development
  #   image: caspnetti_hey
  #   networks:
  #     - caspnetti

  # # Monitoring

  # caspnetti_monitor:
  #   build:
  #     context: ./
  #     dockerfile: ./docker/monitor/Dockerfile
  #   container_name: caspnetti_monitor
  #   image: caspnetti_monitor
  #   networks:
  #     - caspnetti
  #   volumes:
  #     - //var/run/docker.sock:/var/run/docker.sock

networks:

  # External production reverse proxy

  # reproxy:
  #   external: true
  #   name: reproxy

  # Internal container network

  caspnetti:
    name: caspnetti
    driver: bridge
