services:

  # Aspnetcore development

  caspnetti_backend:
    build:
      context: ./
      dockerfile: ./docker/backend/Dockerfile
    container_name: caspnetti_backend
    depends_on:
      - caspnetti_mssql
    env_file:
      - ./docker/backend/.env.local
    image: caspnetti_backend
    # ports:
    #   - 443:443
    volumes:
      - ./src/backend:/caspnetti
    networks:
      - caspnetti

  # MSSQL database

  caspnetti_mssql:
    build:
      context: ./
      dockerfile: ./docker/mssql/Dockerfile
    container_name: caspnetti_mssql
    env_file:
      - ./docker/mssql/.env.local
    image: caspnetti_mssql
    volumes:
      - ./data/mssql:/var/opt/mssql/data
    networks:
      - caspnetti

  # Adminer database viewer

  caspnetti_adminer:
    build:
      context: ./
      dockerfile: ./docker/adminer/Dockerfile
    container_name: caspnetti_adminer
    depends_on:
      - caspnetti_mssql
    env_file:
      - ./docker/adminer/.env.local
    image: caspnetti_adminer
    ports:
      - 8000:8080
    networks:
      - caspnetti

  # Vuejs frontend

  caspnetti_vue_development:
    build:
      context: ./
      dockerfile: ./docker/vue_development/Dockerfile
    container_name: caspnetti_vue_development
    depends_on:
      - caspnetti_backend
    env_file:
      - ./docker/vue_development/.env.local
    image: caspnetti_vue_development
    ports:
      - 8080:8080
    volumes:
      - ./src/frontend:/caspnetti
    networks:
      - caspnetti

  # Vue + nginx production frontend

  # caspnetti_vue_production:
  #   build:
  #     context: ./
  #     dockerfile: ./docker/vue_production/Dockerfile
  #   container_name: caspnetti_vue_production
  #   depends_on:
  #     - caspnetti_backend
  #   env_file:
  #     - ./docker/vue_production/.env.local
  #   image: caspnetti_vue_production
  #   ports:
  #     - 80:80
  #   networks:
  #     - caspnetti

  # Nginx reverse proxy

  caspnetti_nginx:
    container_name: caspnetti_nginx
    build:
      context: ./
      dockerfile: docker/nginx/Dockerfile
    image: caspnetti_nginx
    ports:
      - 443:443
    volumes:
      - ./logs/nginx:/var/log/nginx
    networks:
      # Production reverse proxy
      # - reproxy
      - caspnetti
    restart: unless-stopped

  # Saturation testing

  # caspnetti_hey:
  #   build:
  #     context: ./
  #     dockerfile: ./docker/hey/Dockerfile
  #   container_name: caspnetti_hey
  #   depends_on:
  #     - caspnetti_backend
  #   image: caspnetti_hey
  #   networks:
  #     - caspnetti

  # Monitoring

  # caspnetti_monitor:
  #   build:
  #     context: ./
  #     dockerfile: ./docker/monitor/Dockerfile
  #   container_name: caspnetti_monitor
  #   image: caspnetti_monitor
  #   networks:
  #     - caspnetti
  #   volumes:
  #     - //var/run/docker.sock:/var/run/docker.sock

networks:

  # External production reverse proxy

  # reproxy:
  #   external: true
  #   name: reproxy

  # Internal container network

  caspnetti:
    name: caspnetti
    driver: bridge
