services:

  # Monitoring

  wrychain_monitor:
    build:
      context: ./
      dockerfile: ./docker/monitor/Dockerfile
    container_name: wrychain_monitor
    image: wrychain_monitor
    networks:
      - wrychain
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock
