services:

  # Nginx production reverse proxy

  caspnetti_nginx_production:
    container_name: caspnetti_nginx_production
    build:
      context: ./
      dockerfile: docker/nginx_production/Dockerfile
    depends_on:
      - caspnetti_aspnet_production
    image: caspnetti_nginx_production
    ports:
      - 443:443
    volumes:
      - ./logs/nginx_production:/var/log/nginx
    networks:
      # Production reverse proxy
      - reproxy
      - caspnetti
    # restart: unless-stopped

  # Aspnetcore production

  caspnetti_aspnet_production:
    build:
      context: ./
      dockerfile: ./docker/aspnet_production/Dockerfile
    container_name: caspnetti_aspnet_production
    depends_on:
      - caspnetti_mssql_production
    env_file:
      - ./docker/aspnet_production/.env.local
    image: caspnetti_aspnet_production
    networks:
      - caspnetti

  # MSSQL production database

  caspnetti_mssql_production:
    build:
      context: ./
      dockerfile: ./docker/mssql_production/Dockerfile
    container_name: caspnetti_mssql_production
    env_file:
      - ./docker/mssql_production/.env.local
    image: caspnetti_mssql_production
    volumes:
      - ./data/mssql_production:/var/opt/mssql/data
    networks:
      - caspnetti

  # Vue + nginx production frontend

  caspnetti_vue_production:
    build:
      context: ./
      dockerfile: ./docker/vue_production/Dockerfile
    container_name: caspnetti_vue_production
    depends_on:
      - caspnetti_aspnet_production
    env_file:
      - ./docker/vue_production/.env.local
    image: caspnetti_vue_production
    ports:
      - 80:80
    networks:
      - caspnetti

networks:

  # External production reverse proxy

  reproxy:
    external: true
    name: reproxy
