services:

  wrychain_adminer_development:
    build:
      context: ./
      dockerfile: ./docker/development/adminer/Dockerfile
    container_name: wrychain_adminer_development
    depends_on:
      - wrychain_mssql_development
    env_file:
      - ./docker/development/adminer/.env.local
    image: wrychain_adminer_development
    ports:
      - 8000:8080
    networks:
      - wrychain_development

  wrychain_aspnet_development:
    build:
      context: ./
      dockerfile: ./docker/development/aspnet/Dockerfile
    container_name: wrychain_aspnet_development
    depends_on:
      - wrychain_mssql_development
      - wrychain_redis_development
    env_file:
      - ./docker/development/aspnet/.env.local
    image: wrychain_aspnet_development
    volumes:
      - ./src/backend:/wrychain
    networks:
      - wrychain_development

  wrychain_mssql_development:
    build:
      context: ./
      dockerfile: ./docker/development/mssql/Dockerfile
    container_name: wrychain_mssql_development
    env_file:
      - ./docker/development/mssql/.env.local
    image: wrychain_mssql_development
    volumes:
      - ./docker/development/mssql/data:/var/opt/mssql/data
    networks:
      - wrychain_development

  wrychain_nginx_development:
    container_name: wrychain_nginx_development
    build:
      context: ./
      dockerfile: docker/development/nginx/Dockerfile
    depends_on:
      - wrychain_aspnet_development
    image: wrychain_nginx_development
    ports:
      - 443:443
    volumes:
      - ./docker/development/nginx/logs:/var/log/nginx
    networks:
      - wrychain_development

  wrychain_redis_development:
    build:
      context: ./
      dockerfile: ./docker/development/redis/Dockerfile
    container_name: wrychain_redis_development
    image: wrychain_redis_development
    volumes:
      - ./docker/development/redis/data:/var/lib/redis
    networks:
      - wrychain_development

  wrychain_vue_development:
    build:
      context: ./
      dockerfile: ./docker/development/vue/Dockerfile
    container_name: wrychain_vue_development
    depends_on:
      - wrychain_aspnet_development
    env_file:
      - ./docker/development/vue/.env.local
    image: wrychain_vue_development
    volumes:
      - ./src/frontend:/wrychain
    networks:
      - wrychain_development

networks:

  wrychain_development:
    name: wrychain_development
    driver: bridge
