services:

  # Nginx development reverse proxy

  caspnetti_nginx_development:
    container_name: caspnetti_nginx_development
    build:
      context: ./
      dockerfile: docker/nginx_development/Dockerfile
    depends_on:
      - caspnetti_aspnet_development
    image: caspnetti_nginx_development
    ports:
      - 443:443
    volumes:
      - ./logs/nginx_development:/var/log/nginx
    networks:
      - caspnetti
    # restart: unless-stopped

  # Aspnetcore development

  caspnetti_aspnet_development:
    build:
      context: ./
      dockerfile: ./docker/aspnet_development/Dockerfile
    container_name: caspnetti_aspnet_development
    depends_on:
      - caspnetti_mssql_development
    env_file:
      - ./docker/aspnet_development/.env.local
    image: caspnetti_aspnet_development
    volumes:
      - ./src/backend:/caspnetti
    networks:
      - caspnetti

  # MSSQL development database

  caspnetti_mssql_development:
    build:
      context: ./
      dockerfile: ./docker/mssql_development/Dockerfile
    container_name: caspnetti_mssql_development
    env_file:
      - ./docker/mssql_development/.env.local
    image: caspnetti_mssql_development
    volumes:
      - ./data/mssql_development:/var/opt/mssql/data
    networks:
      - caspnetti

  # Adminer database viewer

  caspnetti_adminer:
    build:
      context: ./
      dockerfile: ./docker/adminer/Dockerfile
    container_name: caspnetti_adminer
    depends_on:
      - caspnetti_mssql_development
    env_file:
      - ./docker/adminer/.env.local
    image: caspnetti_adminer
    ports:
      - 8000:8080
    networks:
      - caspnetti

  # Vuejs frontend

  caspnetti_vue_development:
    build:
      context: ./
      dockerfile: ./docker/vue_development/Dockerfile
    container_name: caspnetti_vue_development
    depends_on:
      - caspnetti_aspnet_development
    env_file:
      - ./docker/vue_development/.env.local
    image: caspnetti_vue_development
    ports:
      - 8080:8080
    volumes:
      - ./src/frontend:/caspnetti
    networks:
      - caspnetti

networks:

  # Internal container network

  caspnetti:
    name: caspnetti
    driver: bridge
