services:

  caspnetti_backend:
    build:
      context: ./
      dockerfile: ./docker/backend/Dockerfile
    container_name: caspnetti_backend
    depends_on:
      - caspnetti_mssql
    env_file:
      - ./docker/backend/.env.local
    image: caspnetti_backend
    ports:
      - 443:443
    volumes:
      - ./src/backend:/caspnetti
    networks:
      - caspnetti

  caspnetti_mssql:
    build:
      context: ./
      dockerfile: ./docker/mssql/Dockerfile
    container_name: caspnetti_mssql
    env_file:
      - ./docker/mssql/.env.local
    image: caspnetti_mssql
    volumes:
      - ./data/mssql:/var/opt/mssql/data
    networks:
      - caspnetti

  caspnetti_adminer:
    build:
      context: ./
      dockerfile: ./docker/adminer/Dockerfile
    container_name: caspnetti_adminer
    depends_on:
      - caspnetti_mssql
    env_file:
      - ./docker/adminer/.env.local
    image: caspnetti_adminer
    ports:
      - 8080:8080
    networks:
      - caspnetti

  caspnetti_vue:
    build:
      context: ./
      dockerfile: ./docker/frontend/Dockerfile
    container_name: caspnetti_vue
    depends_on:
      - caspnetti_backend
    env_file:
      - ./docker/frontend/.env.local
    image: caspnetti_vue
    ports:
      - 8000:8080
    volumes:
      - ./src/frontend:/caspnetti
    networks:
      - caspnetti

  # Saturation testing service

  # caspnetti_hey:
  #   build:
  #     context: ./
  #     dockerfile: ./docker/hey/Dockerfile
  #   container_name: caspnetti_hey
  #   depends_on:
  #     - caspnetti_backend
  #   image: caspnetti_hey
  #   networks:
  #     - caspnetti

  # Monitoring service

  # caspnetti_monitor:
  #   build:
  #     context: ./
  #     dockerfile: ./docker/monitor/Dockerfile
  #   container_name: caspnetti_monitor
  #   image: caspnetti_monitor
  #   networks:
  #     - caspnetti
  #   volumes:
  #     - //var/run/docker.sock:/var/run/docker.sock

networks:
  caspnetti:
    name: caspnetti
    driver: bridge
