services:

  wrychain_adminer_test:
    build:
      context: ./
      dockerfile: ./docker/test/adminer/Dockerfile
    container_name: wrychain_adminer_test
    depends_on:
      - wrychain_mssql_test
    env_file:
      - ./docker/test/adminer/.env.local
    image: wrychain_adminer_test
    ports:
      - 8000:8080
    networks:
      - wrychain_test

  wrychain_aspnet_test:
    build:
      context: ./
      dockerfile: ./docker/test/aspnet/Dockerfile
    container_name: wrychain_aspnet_test
    depends_on:
      - wrychain_mssql_test
    env_file:
      - ./docker/test/aspnet/.env.local
    image: wrychain_aspnet_test
    volumes:
      - ./src/backend:/wrychain
    networks:
      - wrychain_test

  wrychain_mssql_test:
    build:
      context: ./
      dockerfile: ./docker/test/mssql/Dockerfile
    container_name: wrychain_mssql_test
    env_file:
      - ./docker/test/mssql/.env.local
    image: wrychain_mssql_test
    volumes:
      - ./docker/test/mssql/data:/var/opt/mssql/data
    networks:
      - wrychain_test

  wrychain_nginx_test:
    container_name: wrychain_nginx_test
    build:
      context: ./
      dockerfile: docker/test/nginx/Dockerfile
    depends_on:
      - wrychain_aspnet_test
    image: wrychain_nginx_test
    ports:
      - 443:443
    volumes:
      - ./docker/test/nginx/logs:/var/log/nginx
    networks:
      - wrychain_test

  wrychain_vue_test:
    build:
      context: ./
      dockerfile: ./docker/test/vue/Dockerfile
    container_name: wrychain_vue_test
    depends_on:
      - wrychain_aspnet_test
    env_file:
      - ./docker/test/vue/.env.local
    image: wrychain_vue_test
    volumes:
      - ./src/frontend:/wrychain
    networks:
      - wrychain_test

networks:

  wrychain_test:
    name: wrychain_test
    driver: bridge
