services:

  # Monitoring

  caspnetti_monitor:
    build:
      context: ./
      dockerfile: ./docker/monitor/Dockerfile
    container_name: caspnetti_monitor
    image: caspnetti_monitor
    networks:
      - caspnetti
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock
